### ISSUE TITLE
Media Query

### ISSUE THREAD

**Issue by zannain** [illmatic6514/f1-3-c2p1-colmar-academy#1]
In your comment about the media query you say when using `.mobile` or `.secondary` selector. Right now your media query is as follows:

```css
@media only screen and (min-width: 760px) {
  .secondary .box .mobile {
    display: none;
  }
}
```
If I'm understanding correctly you should add a comma between each class name to select them separately as follows:

```css
@media only screen and (min-width: 760px) {
  .secondary, .box, .mobile {
    display: none;
  }
}
```
This will select `.secondary` or `.box` or `.mobile`. Without spaces you are selecting only the grandchildren of `.secondary` that have the class of `.mobile`. You can read more about [CSS Selectors in this article](https://www.w3schools.com/cssref/css_selectors.asp).
